# Type: どのような種類か
- name: "type/enhancement"
  color: "007bff"
  description: "新機能の追加や既存機能の改善"
- name: "type/bug"
  color: "d73a4a"
  description: "期待通りに動作しない不具合"
- name: "type/refactoring"
  color: "6f42c1"
  description: "コード品質を向上させる内部改善"
- name: "type/chore"
  color: "6a737d"
  description: "依存関係を除く日常保守や設定の変更等の作業"
- name: "type/epic"
  color: "1D76DB"
  description: "複数のタスクを束ねる親"
- name: "type/dependencies"
  color: "0366d6"
  description: "依存関係の更新等の作業"

# Area: どの領域に関連するか
- name: "area/client"
  color: "28a745"
  description: "クライアントに関連"
- name: "area/server"
  color: "24292e"
  description: "サーバーに関連"
- name: "area/design"
  color: "db61a2"
  description: "UI/UXデザインに関連"
- name: "area/docs"
  color: "cfd8dc"
  description: "ドキュメントの作成や更新に関連"
- name: "area/infra"
  color: "8B4513"
  description: "開発や本番環境のインフラに関連"
- name: "area/security"
  color: "b60205"
  description: "セキュリティに関連する問題"

# Priority: 優先度はどの程度か
- name: "priority/critical"
  color: "b60205"
  description: "最優先で対応すべき"
- name: "priority/must"
  color: "fbca04"
  description: "リリースに必須"
- name: "priority/should"
  color: "fef2c0"
  description: "対応が推奨される改善"
- name: "priority/could"
  color: "f7f7f7"
  description: "必須ではない改善"

# Need: 必要なアクションは何か
- name: "need/attention"
  color: "ffc107"
  description: "慎重な作業やレビューが必要"
- name: "need/triage"
  color: "FF9800"
  description: "状況整理や優先度の判定が必要"
- name: "need/discussion"
  color: "84DEFF"
  description: "仕様や方針の議論が必要"
- name: "need/help"
  color: "0E8A16"
  description: "助けが必要な状態"
- name: "need/experthelp"
  color: "00C4B3"
  description: "有識者や先輩の助けが必要"
- name: "need/info"
  color: "2196F3"
  description: "追加情報が必要"

# Status: 状態はどうか
- name: "status/blocked"
  color: "E11D21"
  description: "外部要因や依存関係により進行不可"
- name: "status/invalid"
  color: "CFD3D7"
  description: "誤報や再現性がないなど無効"
- name: "status/stale"
  color: "A8A8A8"
  description: "長期間更新がなく停滞"
