name: "Enhancement"
description: "新しい機能や既存機能の改善を提案"
title: "[Enhancement] "
labels: ["type/enhancement", "need/triage"]

body:
  - type: textarea
    id: overview
    attributes:
      label: "Overview"
      description: "どのような機能改善をしたいか、簡潔な概要"
      placeholder: |
        ex. ユーザーがCSVでデータをエクスポートできる機能の実装

  - type: textarea
    id: dev-tasks
    attributes:
      label: "Tasks"
      description: "必要ならタスクを分割"
      placeholder: |
        - [ ] タスク1
        - [ ] タスク2

  - type: textarea
    id: details
    attributes:
      label: "Details"
      description: "補足したい背景・検討内容・設計メモなど"
      placeholder: |
        機能追加の選択肢として、以下も考えられる
          - B案
          - C案

  - type: textarea
    id: references
    attributes:
      label: "References"
      description: "参考情報や、関連情報等あれば"
      placeholder: |
        - #123
        - https://www.figma.com/design/...
